wyswietlanie
richardzmija/complex-maze-path-finding pull request #3
Opened 2024-05-19 10:27 UTC by wtatarek

2024-05-19 12:09 UTC, richardzmija requested changes
Everything looks okay. I suggest separating the code used to generate mazes from the one used to display individual maze. Create a separate module for displaying the maze. Also take into account that we are going to display the ants together with the maze so try to make the code more modular so that it's easier to integrate the ant GUI later on.

2024-05-19 18:38 UTC, wtatarek commented
> Everything looks okay. I suggest separating the code used to generate mazes from the one used to display individual maze. Create a separate module for displaying the maze. Also take into account that we are going to display the ants together with the maze so try to make the code more modular so that it's easier to integrate the ant GUI later on.
> 
> From the stylistic point of view change the name of the pull request so that it describes what you are contributing and use branch names that actually reflect what you are working on. The agreed convention is to use [feature,fix,hotfix]/[descriptive-name-of-your-work]. You should also use hyphens - to separate the individual words in the branch name.

moved to seperate file

2024-05-19 20:34 UTC, richardzmija approved these changes
Good to go

2024-05-20 05:10 UTC, MaciejGrzybacz approved these changes

2024-05-20 09:59 UTC, merged